[package]
name = "rust_quickstart"
version = "0.0.2"
authors = ["Mark Smith <mark.smith@mongodb.com>"]
edition = "2018"

[dependencies]
mongodb = "2"
tokio = "1"
chrono = "0.4"
serde = "1"
serde_json = "1"
futures = "0.3"